---
shortname: cypher
action: true
coqdoc: true
coqdoc_index: 'docs/latest/coqdoc/toc.html'

license:
  fullname: GNU Lesser General Public License v2.1 or later
  identifier: LGPL-2.1-or-later

supported_coq_versions:
  text: 8.12 or later
  opam: '{(>= "8.12" & < "8.17~") | (= "dev")}'
  
dependencies:
- opam:
    name: coq-relation-algebra
    version: '{(>= "1.7.7") | (= "dev")}'
  description: |-
    [relation algebra](http://perso.ens-lyon.fr/damien.pous/ra) 1.7.0 or later (`ssreflect` suffices)

tested_coq_opam_versions:
- version: 'dev'
- version: '8.15'

ci_cron_schedule: '10 1 * * 0'


