name: building
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
      matrix:
        coq_version:
          - '8.16'
          - dev
        ocaml_version: ['default']
        fail-fast: false
  steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: 'folder/coq-proj.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
