name: Docker CI

on:
  schedule:
    - cron: '10 1 * * 0'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        coq_version:
          - '8.15'
        ocaml_version:
          - '4.11.2'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Try to restore opam cache
        if: runner.os != 'Windows'
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}

      - name: Add packages sources
        run: opam repo add coq-released https://coq.inria.fr/opam/released && opam remote add coq-weakmemory-local -k git https://github.com/weakmemory/local-coq-opam-archive
      
      - name: Install dependencies
        run: opam install . --deps-only --yes
      
      - name: Run linter
        run: make lint

      - name: Build theories
        run: opam exec -- dune build
